<template>
    <div class="small">
      <ConvButton
        left="F"
        right="(F)"
        conversionTypeL="LS0_1"
        conversionTypeR="LS0_2"
      ></ConvButton>
      <ConvButton
        left="F∧F"
        right="F"
        conversionTypeL="LS1_1"
        conversionTypeR="LS1_2"
      ></ConvButton>
      <ConvButton
        left="F∨F"
        right="F"
        conversionTypeL="LS2_1"
        conversionTypeR="LS2_2"
      ></ConvButton>
      <ConvButton
        left="F∧G"
        right="G ∧ F"
        conversionTypeL="LS3"
        conversionTypeR="LS3"
      ></ConvButton>
      <ConvButton
        left="F∨G"
        right="G∨F"
        conversionTypeL="LS4"
        conversionTypeR="LS4"
      ></ConvButton>
      <ConvButton
        left="(F∧G)∧H"
        right="F∧(G∧H)"
        conversionTypeL="LS5_1"
        conversionTypeR="LS5_2"
      ></ConvButton>
      <ConvButton
        left="(F∨G)∨H"
        right="F∨(G∨H)"
        conversionTypeL="LS6_1"
        conversionTypeR="LS6_2"
      ></ConvButton>
      <ConvButton
        left="F∧(F∨G)"
        right="F"
        conversionTypeL="LS7_1"
        conversionTypeR="LS7_2"
      ></ConvButton>
      <ConvButton
        left="F∨F∧G"
        right="F"
        conversionTypeL="LS8_1"
        conversionTypeR="LS8_2"
      ></ConvButton>
    </div>
    <div class="medium">
      <ConvButton
        left="F∧(G∨H)"
        right="F∧G∨F∧H"
        conversionTypeL="LS9_1"
        conversionTypeR="LS9_2"
      ></ConvButton>
      <ConvButton
        left="F∨G∧H"
        right="(F∨G)∧(F∨H)"
        conversionTypeL="LS10_1"
        conversionTypeR="LS10_2"
      ></ConvButton>
      <ConvButton
        left="¬(F∧G)"
        right="¬F∨¬G"
        conversionTypeL="LS11_1"
        conversionTypeR="LS11_2"
      ></ConvButton>
      <ConvButton
        left="¬(F∨G)"
        right="¬F∧¬G"
        conversionTypeL="LS12_1"
        conversionTypeR="LS12_2"
      ></ConvButton>
      <ConvButton
        left="F⇒G"
        right="¬(F∧¬G)"
        conversionTypeL="LS13_1"
        conversionTypeR="LS13_2"
      ></ConvButton>
      <ConvButton
        left="F⇒G"
        right="¬F∨G"
        conversionTypeL="LS14_1"
        conversionTypeR="LS14_2"
      ></ConvButton>
      <ConvButton
        left="F∧G"
        right="¬(F⇒G)"
        conversionTypeL="LS15_1"
        conversionTypeR="LS15_2"
      ></ConvButton>
      <ConvButton
        left="F∨G"
        right="¬F⇒G"
        conversionTypeL="LS16_1"
        conversionTypeR="LS16_2"
      ></ConvButton>
    </div>
    <div class="large">
      <ConvButton
        left="F⇔G"
        right="F∧G∨¬F∧¬G"
        conversionTypeL="LS17_1"
        conversionTypeR="LS17_2"
      ></ConvButton>
      <ConvButton
        left="F⇔G"
        right="(F⇒G)∧(G⇒F)"
        conversionTypeL="LS18_1"
        conversionTypeR="LS18_2"
      ></ConvButton>
      <ConvButton
        left="F∧1"
        right="F"
        conversionTypeL="LS19_1"
        conversionTypeR="LS19_2"
      ></ConvButton>
      <ConvButton
        left="F∨1"
        right="1"
        conversionTypeL="LS20_1"
        conversionTypeR="LS20_2"
      ></ConvButton>
      <ConvButton
        left="F∧0"
        right="0"
        conversionTypeL="LS21_1"
        conversionTypeR="LS21_2"
      ></ConvButton>
      <ConvButton
        left="F∨0"
        right="F"
        conversionTypeL="LS22_1"
        conversionTypeR="LS22_2"
      ></ConvButton>
      <ConvButton
        left="¬¬F"
        right="F"
        conversionTypeL="LS23_1"
        conversionTypeR="LS23_2"
      ></ConvButton>
      <ConvButton
        left="F⇔G"
        right="G⇔F"
        conversionTypeL="LS24"
        conversionTypeR="LS24"
      ></ConvButton>
    </div>
  
</template>

<script>
import ConvButton from "./ConvButton.vue";

export default {
    name: "PropositionalLogicButtons",
    data() {
        return {}
    },
    components: {
        ConvButton
    }

}
</script>

<style>
</style>